/**
 * Amplify bootstrap
 * Loads configuration from amplify_outputs.json generated by `ampx sandbox/deploy`.
 * This file must be imported BEFORE app mount.
 */
import { Amplify } from 'aws-amplify'

// Carrega outputs do arquivo existente na raiz do projeto.
// Em ambientes onde o arquivo ainda não existe, fazemos fallback para objeto vazio
// para permitir build sem quebrar tipos (sem usar any).
type AmplifyOutputs = Record<string, unknown>
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
let outputs: AmplifyOutputs
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  outputs = require('../amplify_outputs.json') as AmplifyOutputs
} catch {
  outputs = {}
}

Amplify.configure(outputs)
