/**
 * Amplify bootstrap
 * Loads configuration from amplify_outputs.json generated by `ampx sandbox/deploy`.
 * This file must be imported BEFORE app mount.
 *
 * Observação:
 * - O arquivo amplify_outputs.json está na raiz do projeto (fora de src),
 *   por isso o caminho relativo usa '../../'.
 */
import { Amplify } from 'aws-amplify'
import outputs from '../../amplify_outputs.json'

Amplify.configure(outputs)
